services:
  - type: web
    name: sp-korea-api-products
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port ${PORT}
    envVars:
      - key: PORT
        sync: false  # Render сам подставит
    disk:
      name: api-data
      mountPath: /var/data
      sizeGB: 1